### Numpy
**NumPy (Numerical Python) is the foundational open-source library used for scientific computing and high-performance array manipulation in Python. It introduces the ndarray (N-dimensional array) object, which processes numerical data up to 50 times faster than traditional Python lists by using contiguous memory and optimized C-code under the hood**

In [47]:
import numpy as np  # np is alias for numpy

In [48]:
# create array using numpy
# create 1-d array
arr1 = np.array([1,2,3,4,5])

print(arr1)
print(arr1.shape)
print(arr1.ndim)
print(type(arr1))

[1 2 3 4 5]
(5,)
1
<class 'numpy.ndarray'>


In [49]:
## reshaping
arr2 = np.array([1,2,3,4,5])

print(arr2.reshape((1,5)))
print(arr2.shape)
print(arr2.ndim)

[[1 2 3 4 5]]
(5,)
1


In [50]:
# 2-d array
arr2 = np.array([[1,2,3,4,5], [5,4,3,2,1]])

print(arr2)
print(arr2.shape)
print(arr2.ndim)

[[1 2 3 4 5]
 [5 4 3 2 1]]
(2, 5)
2


In [51]:
np.arange(0,10,2).reshape((5,1))

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [52]:
# inbuild methods
np.ones(4, dtype=np.int32)

array([1, 1, 1, 1], dtype=int32)

In [53]:
np.zeros((2,4), dtype='int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [54]:
# identity matrix
identity = np.eye(3)

print('our identity matrix is:\n', identity)
print('shape of an array:', identity.shape)
print('dimension of an array:', identity.ndim)
print('size of an array, that is total number of elements:', identity.size)
print('data type of an array:', identity.dtype)
print('itemsize of an array (in bytes):', identity.itemsize)

our identity matrix is:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
shape of an array: (3, 3)
dimension of an array: 2
size of an array, that is total number of elements: 9
data type of an array: float64
itemsize of an array (in bytes): 8


In [55]:
# Numpy vectorized operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# element wise addition
print(arr1 + arr2)

# element wise Substraction
print(arr1 - arr2)

# element wise Multiplication
print(arr1 * arr2)

# element wise division
print(arr1 / arr2)

# element wise Modulo/remainder
print(arr1 % arr2)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]
[1 2 3 4 5]


In [56]:
arr1 + 20

array([21, 22, 23, 24, 25])

In [57]:
# Universal function(ufuncs)
arr = np.array([1,2,3,4,5])

# square root
print(np.sqrt(arr))

# Exponential
print(np.exp(arr))

# Sine
print(np.sin(arr))

# Natural log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [58]:
# array slicing and indexing
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("Array: \n", arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [59]:
arr[1][2]

np.int64(7)

In [60]:
arr[:][2]

array([ 9, 10, 11, 12])

In [61]:
arr[1:, 2:]

array([[ 7,  8],
       [11, 12]])

In [62]:
arr[:2, 2:]

array([[3, 4],
       [7, 8]])

In [63]:
arr[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [64]:
arr[0, 0] = 100
arr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [65]:
arr[1:] = 123
arr

array([[100,   2,   3,   4],
       [123, 123, 123, 123],
       [123, 123, 123, 123]])

In [70]:
# Statistical concept - Normalization
# is to convert the data inro "mean of zero(0) and staandar deviation of one(1)"
data = np.array([1,2,3,4,5])

# calculate the meand and std
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev

print(f'Original data = {data}')
print(f'{normalized_data = }')

Original data = [1 2 3 4 5]
normalized_data = array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])


In [76]:
print(f'{np.mean(data) = }')
print(f'{np.median(data) = }')
print(f'{np.std(data) = }')
print(f'{np.var(data) = }')

np.mean(data) = np.float64(3.0)
np.median(data) = np.float64(3.0)
np.std(data) = np.float64(1.4142135623730951)
np.var(data) = np.float64(2.0)


In [83]:
# logical opearion
arr = np.array([1,2,3,4,5,6,7,8,9,10])

# elements > 5
print(arr[arr > 5])  # boolean masking

# data between 5 and 8
print(arr[(arr > 5) & (arr <= 8)])

[ 6  7  8  9 10]
[6 7 8]
